-- Execute este script no SQL Editor do seu Dashboard no Supabase

-- 1. Criação da Tabela de Tarefas
CREATE TABLE IF NOT EXISTS chronos_tasks (
  id NUMERIC PRIMARY KEY, 
  title TEXT NOT NULL,
  time TEXT,
  type TEXT,
  done BOOLEAN DEFAULT FALSE,
  note TEXT,
  date TEXT,
  end_date TEXT,
  alarm_time TEXT,
  alarm_enabled BOOLEAN DEFAULT FALSE,
  recurrence TEXT DEFAULT 'none'
);

-- 2. Criação da Tabela de Eventos Personalizados
CREATE TABLE IF NOT EXISTS chronos_custom_events (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  date TEXT,
  end_date TEXT,
  logo TEXT,
  emoji TEXT,
  category TEXT,
  border_color TEXT,
  recurrence TEXT,
  description TEXT,
  details JSONB
);

-- 3. Criação da Tabela de Substituição de Eventos (Overrides)
CREATE TABLE IF NOT EXISTS chronos_event_overrides (
  id TEXT PRIMARY KEY,
  name TEXT,
  border_color TEXT,
  custom_logo TEXT
);

-- 4. Criação da Tabela de Categorias de Cores
CREATE TABLE IF NOT EXISTS chronos_color_categories (
  id NUMERIC PRIMARY KEY,
  name TEXT,
  color TEXT
);

-- Inserindo categorias padrão
INSERT INTO chronos_color_categories (id, name, color) VALUES 
  (1, 'Trabalho', '#E53935'),
  (2, 'Descanso', '#1E88E5'),
  (3, 'Contas', '#FDD835'),
  (4, 'Estudo', '#43A047'),
  (5, 'Pessoal', '#AB47BC')
ON CONFLICT (id) DO NOTHING;

-- 5. Criação da Tabela de Cores do Dia
CREATE TABLE IF NOT EXISTS chronos_day_colors (
  date_key TEXT PRIMARY KEY,
  cat_id NUMERIC
);

-- 6. Criação da Tabela de Configurações Genéricas
CREATE TABLE IF NOT EXISTS chronos_settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- 7. Criação do Histórico do Oráculo
CREATE TABLE IF NOT EXISTS chronos_chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT,
  text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
